name: 'AOSP Build setup'
description: 'Add build prerequisites for android'
inputs:
  test-input:  # id of input
    description: 'Test of input param'
    required: true
    default: 'DFL'
runs:
  using: "composite"
  steps:
    - run: echo Hello you added ${{ inputs.test-input }}.
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: test-action.sh ${{ inputs.test-input }}
      shell: bash
